version: "2.1"
services:
  elasticsearch:
    build:
      dockerfile: Dockerfile
      context: .
    image: samwang0723/docker-elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    tty: true
